export const SERVER_VALUES = {
    eun1: "EUNE",
    euw1: "EUW",
    tr1: "TR",
    ru: "RU",
    na1: "NA",
    la1: "LAN",
    la2: "LAS",
    br1: "BR",
    oc1: "OCE",
    jp1: "JP",
    kr: "KR",
    ph2: "PH",
    sg2: "SG",
    th2: "TH",
    tw2: "TW",
    vn2: "VN",
};
